# Generated by Django 4.1 on 2023-06-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_delete_contact_remove_order_arrive_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='family_name',
        ),
    ]
