# Generated by Django 4.1 on 2023-07-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_first_name_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
